"""Add response_data to strategy tables

Revision ID: 024d7df44a14
Revises: 07f065ceb75c
Create Date: 2025-07-28 16:37:39.846920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "024d7df44a14"
down_revision: Union[str, Sequence[str], None] = "07f065ceb75c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column(
        "strategy_open_trades", sa.Column("response_data", sa.JSON(), nullable=True)
    )
    op.add_column(
        "strategy_trades", sa.Column("response_data", sa.JSON(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy_trades", "response_data")
    op.drop_column("strategy_open_trades", "response_data")
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
