"""Rebuild models with verification fields

Revision ID: 076a03bc40b9
Revises: ba36e1f88c74
Create Date: 2025-08-05 18:47:09.104148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '076a03bc40b9'
down_revision: Union[str, Sequence[str], None] = 'ba36e1f88c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_signals', 'received_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_strategy_open_trades_status'), 'strategy_open_trades', ['status'], unique=False)
    op.alter_column('strategy_trades', 'open_trade_public_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('strategy_trades', 'realized_pnl',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=False)
    op.create_foreign_key(None, 'strategy_trades', 'strategy_open_trades', ['open_trade_public_id'], ['public_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'strategy_trades', type_='foreignkey')
    op.alter_column('strategy_trades', 'realized_pnl',
               existing_type=mysql.DECIMAL(precision=18, scale=8),
               nullable=True)
    op.alter_column('strategy_trades', 'open_trade_public_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.drop_index(op.f('ix_strategy_open_trades_status'), table_name='strategy_open_trades')
    op.alter_column('raw_signals', 'received_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('current_timestamp()'),
               existing_nullable=False)
    # ### end Alembic commands ###
