"""add fund_manager_id to strategy tables

Revision ID: 07f065ceb75c
Revises: 1f1d2fb58a3b
Create Date: 2025-07-28 15:52:39.712116

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "07f065ceb75c"
down_revision: Union[str, Sequence[str], None] = "1f1d2fb58a3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column(
        "strategy_open_trades",
        sa.Column("fund_manager_id", sa.String(length=64), nullable=False),
    )
    op.add_column(
        "strategy_trades",
        sa.Column("fund_manager_id", sa.String(length=64), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy_trades", "fund_manager_id")
    op.drop_column("strategy_open_trades", "fund_manager_id")
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
