"""Add pending/verification fields and exchange_order_id

Revision ID: 1160387fe8a3
Revises: 076a03bc40b9
Create Date: 2025-08-05 19:01:46.728893

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1160387fe8a3"
down_revision: Union[str, Sequence[str], None] = "076a03bc40b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "strategy_open_trades",
        "unrealized_pnl",
        existing_type=mysql.DECIMAL(precision=18, scale=8),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "strategy_open_trades",
        "unrealized_pnl",
        existing_type=mysql.DECIMAL(precision=18, scale=8),
        nullable=True,
    )
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
