"""add exchange column to strategy tables

Revision ID: 1f1d2fb58a3b
Revises: 3eb8b25f3944
Create Date: 2025-07-28 15:31:18.286955

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "1f1d2fb58a3b"
down_revision: Union[str, Sequence[str], None] = "3eb8b25f3944"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column(
        "strategy_open_trades",
        sa.Column("exchange", sa.String(length=16), nullable=False),
    )
    op.add_column(
        "strategy_trades", sa.Column("exchange", sa.String(length=16), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("strategy_trades", "exchange")
    op.drop_column("strategy_open_trades", "exchange")
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
