"""Your next change

Revision ID: 3eb8b25f3944
Revises: 20a331d96d22
Create Date: 2025-07-27 04:50:59.862881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3eb8b25f3944"
down_revision: Union[str, Sequence[str], None] = "20a331d96d22"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column(
        "strategy_open_trades",
        sa.Column("public_id", sa.String(length=36), nullable=False),
    )
    op.create_index(
        op.f("ix_strategy_open_trades_public_id"),
        "strategy_open_trades",
        ["public_id"],
        unique=True,
    )
    op.add_column(
        "strategy_trades", sa.Column("public_id", sa.String(length=36), nullable=False)
    )
    op.create_index(
        op.f("ix_strategy_trades_public_id"),
        "strategy_trades",
        ["public_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_strategy_trades_public_id"), table_name="strategy_trades")
    op.drop_column("strategy_trades", "public_id")
    op.drop_index(
        op.f("ix_strategy_open_trades_public_id"), table_name="strategy_open_trades"
    )
    op.drop_column("strategy_open_trades", "public_id")
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
