"""Increase exchange field length

Revision ID: 541fa9870fda
Revises: ef846562f771
Create Date: 2025-08-03 19:25:44.341312

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "541fa9870fda"
down_revision: Union[str, Sequence[str], None] = "ef846562f771"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "strategy_open_trades",
        "exchange",
        existing_type=mysql.VARCHAR(length=16),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    op.alter_column(
        "strategy_trades",
        "leverage",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "strategy_trades",
        "leverage",
        existing_type=mysql.INTEGER(display_width=11),
        nullable=True,
    )
    op.alter_column(
        "strategy_open_trades",
        "exchange",
        existing_type=sa.String(length=64),
        type_=mysql.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
