"""add open_trade_public_id to StrategyTrade (nullable first)

Revision ID: db533d7c9dfa
Revises: efc05fe65026
Create Date: 2025-08-04 10:18:32.066465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "db533d7c9dfa"
down_revision: Union[str, Sequence[str], None] = "efc05fe65026"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.add_column(
        "strategy_trades",
        sa.Column("open_trade_public_id", sa.String(length=36), nullable=True),
    )
    op.create_index(
        op.f("ix_strategy_trades_open_trade_public_id"),
        "strategy_trades",
        ["open_trade_public_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_strategy_trades_open_trade_public_id"), table_name="strategy_trades"
    )
    op.drop_column("strategy_trades", "open_trade_public_id")
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
