"""Increase exchange field length

Revision ID: efc05fe65026
Revises: 541fa9870fda
Create Date: 2025-08-03 20:04:21.755976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "efc05fe65026"
down_revision: Union[str, Sequence[str], None] = "541fa9870fda"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("now()"),
        existing_nullable=False,
    )
    op.alter_column(
        "strategy_trades",
        "exchange",
        existing_type=mysql.VARCHAR(length=16),
        type_=sa.String(length=64),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "strategy_trades",
        "exchange",
        existing_type=sa.String(length=64),
        type_=mysql.VARCHAR(length=16),
        existing_nullable=False,
    )
    op.alter_column(
        "raw_signals",
        "received_at",
        existing_type=mysql.DATETIME(),
        server_default=sa.text("current_timestamp()"),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
